- name: Comparing var-files and Task level variables
  hosts: localhost
  connection: local
  vars_files:
   - variables.yaml
  tasks:
   - name: Executing varfiles and Task varibales
     vars:
      NAME: Manojkumar - Task
      CITY: Chennai - Task
     debug:
      msg: "My name is {{ NAME }}. I am living in {{ CITY }}"


- name: Comparing var-files and playbook level variables
  hosts: localhost
  connection: local
  vars:
   NAME: Manoj - Playbook
   CITY: Tirupati - Playbook
  vars_files:
   - variables.yaml
  tasks:
   - name: Executing varfiles and playbook varibales
     debug:
      msg: "My name is {{ NAME }}. I am living in {{ CITY }}"

