- name: even or odd
  hosts: local
  connection: local
  vars_prompt:
    - name: given_number
      prompt: "Type your number"
      private: false  #by default it is taken as private, private means text is hidden
  tasks:
    - name: checking the number is even or odd
      debug:
        msg: "The given number is {{ given_number }} and it is even"
      when: given_number | int % 2 == 0


    - name: checking the number is even or odd
      debug:
        msg: "The given number is {{ given_number }} and it is odd"
      when: given_number | int % 2 != 0
 