- name : looping playbook
  hosts: local
  connection: local
  tasks:
    - name: displaying names
      debug:
        msg: "Blood relations are {{ item }}"
      loop:
        - Sai
        - Padmavathi
        - Sudhakar


- name : Installing apps and started the services
  hosts: Node
  become: yes
  tasks:
    - name: Installing applications
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - mysql-server
        - git
        




       